# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qASBaBScQs6Ka2iNeXx4vFRIWuvQ9eI
"""



import pyranges as pr
import pandas as pd
import os

H = ["chrom",  "chromStart", "chromEnd", "strand", "gene_symbol", "entrez_gene_id", "transcript_id" , "raw_count", "scaled_estimate", "normalized_count", "barcode"]
list = os.listdir("E:\\newdata")   
#extract the barcode 
code =[]
for f in list:
    x = '-'.join(f.split('-')[0:3])
    code.append(x)
print('2')  
 #find direction of each bed file
newList=[]
for i in range(len(list)):
    newList.append("E:\\newdata\\" + list[i])
print('3')  
#read the bed files one after another, save it in file and add barcode

for bed in newList: #bed file in newlist
    for n in code: 
        df = pr.read_bed(bed, as_df=True)
        df['barcode'] = n
        filename = df.to_csv('E:\\data951.csv',mode ='a', header = H, index=False)


print("done")